services:
  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./db.env
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - db

  nest:
    build:
      context: ../
      dockerfile: ./apps/backend/api/Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - ./nest.env
    environment:
      - NODE_ENV=production
    networks:
      - backend
      - db

  client: 
    build:
      context: ../
      dockerfile: ./apps/frontend/web/Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - web-client-build:/app/apps/frontend/web/dist

  web:
    image: nginx:1.23.2-alpine
    depends_on:
      - nest
      - client
    restart: always
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build:ro
    ports:
      - ${GATEWAY_PORT:-8000}:80
    networks:
      - backend

volumes:
  web-client-build:

networks:
  backend:
  db:
