services:
  db:
    image: mysql:8.0.31
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./db.env
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - db

  nest:
    # To replace with the correct path of your server image
    # image: dockerhub-username/nest-image
    restart: always
    depends_on:
      - db
    env_file:
      - ./nest.env
    networks:
      - backend
      - db

  client: 
    # To replace with the correct path of your server image
    # image: dockerhub-username/client-image
    volumes:
      - web-client-build:/app

  web:
    image: nginx:1.23.2-alpine
    depends_on:
      - nest
      - client
    restart: always
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build:ro
    ports:
      - ${GATEWAY_PORT:-8000}:80
    networks:
      - backend

volumes:
  web-client-build:

networks:
  backend:
  db:
